/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddArac: typeof import('./src/components/AddArac.vue')['default']
    AdminArac: typeof import('./src/components/AdminArac.vue')['default']
    AdminPanel: typeof import('./src/components/AdminPanel.vue')['default']
    AracDetay: typeof import('./src/components/AracDetay.vue')['default']
    'BizeUlasın': typeof import('./src/components/BizeUlasın.vue')['default']
    CarResult: typeof import('./src/components/CarResult.vue')['default']
    Filomuz: typeof import('./src/components/Filomuz.vue')['default']
    FooterComponent: typeof import('./src/components/FooterComponent.vue')['default']
    Hakkimizda: typeof import('./src/components/Hakkimizda.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    InsuranceAndServices: typeof import('./src/components/InsuranceAndServices.vue')['default']
    Kirala: typeof import('./src/components/Kirala.vue')['default']
    KullaniciListele: typeof import('./src/components/KullaniciListele.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    'LoginForm.': typeof import('./src/components/LoginForm..vue')['default']
    NavbarComponent: typeof import('./src/components/NavbarComponent.vue')['default']
    OdemeListele: typeof import('./src/components/OdemeListele.vue')['default']
    Payment: typeof import('./src/components/Payment.vue')['default']
    RegisterForm: typeof import('./src/components/RegisterForm.vue')['default']
    ReservationDetails: typeof import('./src/components/ReservationDetails.vue')['default']
    ReservationForm: typeof import('./src/components/ReservationForm.vue')['default']
    RezervasyonListele: typeof import('./src/components/RezervasyonListele.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
